name = "stripe-redirect-proxy"
main = "worker.js"
compatibility_date = "2024-03-15"

# Add your domain for the worker
routes = [
  { pattern = "stripe-redirect-proxy.YOUR_SUBDOMAIN.workers.dev", custom_domain = false }
]

[vars]
ENVIRONMENT = "production"

# Headers should be defined differently in Wrangler
# They will be set in the worker code instead